// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwx1iAdA9HR7OtOeais-o7k4C4OLRMe0A',
    appId: '1:588961643605:web:06f0a9aa0068ac18bae8dc',
    messagingSenderId: '588961643605',
    projectId: 'andando-staging',
    authDomain: 'andando-staging.firebaseapp.com',
    storageBucket: 'andando-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv-8X20rmofqTJQahwcbClKj0yOMDzNk',
    appId: '1:588961643605:android:71edd9eba46b0586bae8dc',
    messagingSenderId: '588961643605',
    projectId: 'andando-staging',
    storageBucket: 'andando-staging.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADyPBx70ccu7Ynd7cql1eRHUMSQss7msM',
    appId: '1:588961643605:ios:b9ecc6dbec46f89cbae8dc',
    messagingSenderId: '588961643605',
    projectId: 'andando-staging',
    storageBucket: 'andando-staging.firebasestorage.app',
    iosBundleId: 'com.andando.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADyPBx70ccu7Ynd7cql1eRHUMSQss7msM',
    appId: '1:588961643605:ios:b9ecc6dbec46f89cbae8dc',
    messagingSenderId: '588961643605',
    projectId: 'andando-staging',
    storageBucket: 'andando-staging.firebasestorage.app',
    iosBundleId: 'com.andando.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwx1iAdA9HR7OtOeais-o7k4C4OLRMe0A',
    appId: '1:588961643605:web:a06efac5b26a87e8bae8dc',
    messagingSenderId: '588961643605',
    projectId: 'andando-staging',
    authDomain: 'andando-staging.firebaseapp.com',
    storageBucket: 'andando-staging.firebasestorage.app',
  );
}
